version: '3.8'

services:
  db:
    image: postgres
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_DB: meu_projeto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 🔥 Volume para persistência do banco

  web:
    build: .
    container_name: meu_django
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:minha_senha@db:5432/meu_projeto
    volumes:
      - .:/app  # 🔥 Esse volume deve estar dentro do "web"

volumes:
  postgres_data:  # 🔥 Declaração do volume para o banco